---
- name: This playbook demonstrates applying a hotfix on a Windows host over openssh
  hosts: Greg-win-iis-openssh
  gather_facts: no
  vars:
    msu_path: C:\Users\Administrator\Downloads\windows11.0-kb5065426-x64_32b5f85e0f4f08e5d6eabec6586014a02d3b6224.msu
    kb_id: KB5065426

  tasks:
    # - name: Copy hotfix file to remote Windows host
    #   ansible.builtin.copy:
    #     src: /path/to/local/hotfix.msu
    #     dest: C:\Temp\hotfix.msu

    - ansible.windows.win_shell: |
        Get-HotFix | Select-Object Description, HotFixID, InstalledOn | ConvertTo-Json -Depth 2
      register: hotfixes_raw

    - ansible.builtin.debug:
        msg: "{{ hotfixes_raw.stdout | from_json }}"

    # - name: Apply the hotfix using wusa.exe
    #   ansible.builtin.win_command: "wusa.exe {{ msu_path }} /quiet /norestart"
    #   #when the system asks for a restart it returns exit code 3010, so not failure.
    #   changed_when: wusa.rc in [0, 3010]
    #   failed_when: wusa.rc not in [0, 3010, 2359302]  #2359302 = already installed
    #   become: true
    #   register: wusa

    - name: Install MSU idempotently
      ansible.windows.win_hotfix:
        source: "{{ msu_path }}"
        hotfix_kb: "{{ kb_id }}"
        state: present
      register: hf
      # (optional elevation—same rules apply)
      become: true

    # - name: Remove the hotfix file after installation
    #   ansible.builtin.file:

    - ansible.windows.win_shell: |
        Get-HotFix | Select-Object Description, HotFixID, InstalledOn | ConvertTo-Json -Depth 2
      register: hotfixes_raw

    - ansible.builtin.debug:
        msg: "{{ hotfixes_raw.stdout | from_json }}"
